### ISSUE TITLE
SOS:the device management client of wince is used to download/install application

### ISSUE THREAD

**Issue by YoKoa** [enwony/wince-mdm-server#2]
it(device management client) can report and download application,I wanna to know how to make 
Download feature,can you help me?I'll always appreciate that.

**Comment by enwony** [comment]
Hi there! This project is not finished (just a prototype), I'm currently out of focus for this project.
Look like I implement model and "get device info" only.
If you want to implement download, you should clone this project or pull change request.

Developed using flask + sqlalchemy, to implement download you should code webapp::DownloadEventStatusReport and webapp::InstructionRequest

**Comment by YoKoa** [comment]
Thank you for your reply
But I dont know what the xml of InstructionRequest and  DownloadEventStatusReport is.
Do you have a example? 
Thank you v...very much.

**Comment by enwony** [comment]
I used documentation from https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms894462(v=msdn.10)
XML events examples here https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms894701(v=msdn.10)
Not perfectly documented(lack of details), but here we are.

**Comment by YoKoa** [comment]
I'll read these document,and I'll always appreciate that.
